### ISSUE TITLE
[Moving platforms] More velocity when walking towards the direction they are moving

### ISSUE THREAD

**Issue by JaumeMontagut** [thedoctormarc/DOOM_2D19#34]
**Bug description**
Moving platforms give you more velocity when walking towards the direction they are moving.

**Expected behaviour**
You move with the same velocity going to the direction the platform is moving that on the opposite.

**Game version**
0.4

**Comment by thedoctormarc** [comment]
You actually have a relative speed to the platform, meaning that if you stay idle, the platform drags you (otherwise you would be all the time fighting against the platform speed), thus when you move, the speed is added to the platform current speed. 
This gives a nice ilussion when you jump, and the fall, the horizontal platform will have advances its position, because you have its reference system
