### ISSUE TITLE
[Sprites] The character moves their legs as if they were walking when they are on the air

### ISSUE THREAD

**Issue by JaumeMontagut** [thedoctormarc/DOOM_2D19#44]
**Steps to reproduce**
1. Jump
2. Move the joystick to one of the sides.

**Expected behaviour**
The character moves to that direction, but doesn't move its legs.

**Actual behaviour**
The character goes where I need them to go, but it moves his feet while in the air.

**Game version**
0.4

**Aditional context**
It looks like Luigi when he extends his jump by moving his

**Comment by thedoctormarc** [comment]
Actually, this is expected as the original game.
It is plausible to make him not move them, but this is very DOOM-ish stuff, the player keeps running as metaphore such as "the action does not stop", he just keeps going, and its satisfactory because you see him running and you are waiting for him to just hit the floor and start running again, so there is some odd satisfaction for sure (I'm a weird guy I know)
